name: Node.js CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: ls
    # - run: sh deploy.sh
    - run: cd packages/docs
    - run: ls
    - run: npm install
    - run: npm run docs:build
    - run: cd .vitepress/dist
    - run: git init 
    - run: git add -A 
    - run: git commit -m 'deploy'
    - run: git push -f git@github.com:Tao0929/easy-draw-ui.git main:gh-pages